<script setup>
	import "dayjs/locale/es";
	import dayjs from 'dayjs';
	import { ref, watch } from 'vue';
	import { Button, DatePicker, message, Modal, RangePicker, Tooltip, Select, Carousel, SelectOption, Space } from 'ant-design-vue';
	import { InfoCircleOutlined, ClockCircleOutlined, CalendarOutlined, LeftCircleOutlined, RightCircleOutlined } from '@ant-design/icons-vue';
	import { usePage, router } from "@inertiajs/vue3";
	import axios from "axios";
	import ReservaEstado from "./ReservaEstado.vue";

	dayjs.locale('es');

	const page = usePage()

	const props = defineProps({
		recurso: Array,
		open: Boolean,
		tipo: String
	});

	const emitir = defineEmits(['send','close']);
	const recurso = ref(props.recurso ?? {});
	const tipo = ref(props.tipo)
	const cargando = ref(false)
	const tiempo = ref('')
	const disabled = ref(true)
	const reservas = ref([])
	const fecha = ref(dayjs())

	const data = {
		hora_inicio: null,
		hora_fin: null,
	}

	watch(() => props.open, (val)=>{
		if (val) {
			recurso.value = { ...props.recurso };
			console.log(recurso.value);
			tipo.value = props.tipo;
			cargando.value = true
			reservas.value = [];
			axios.get(`/api/reservas/${tipo.value}/${recurso.id}`)
				.then(({ data }) => {
					// Serealizando
					data.reservas = data.reservas.map((reserva) => {
						return {
							...reserva,
							hora_inicio: new Date(reserva.hora_inicio),
							hora_fin: new Date(reserva.hora_fin),
						}
					})
					reservas.value = data.reservas

					cargando.value = false

					// Invalid
					recurso.value.fotos = [
						{id:3,ruta: 'https://raw.githubusercontent.com/vueComponent/ant-design-vue/main/components/carousel/demo/abstract04.jpg'},
						{id:30,ruta: 'https://raw.githubusercontent.com/vueComponent/ant-design-vue/main/components/carousel/demo/abstract02.jpg'}
					]

					if (recurso.value.fotos.length < 1) {
						recurso.value.fotos = [
							{	id: 1, ruta: 'https://www.nbmchealth.com/wp-content/uploads/2018/04/default-placeholder.png'},
						]
					}

					console.log(recurso.value);

					horasLimit.value = horasLimit.value.map()
					for (const reserva of reservas.value) {
						for (const limit of horasLimit) {
							if (reserva.hora_inicio.getHours() >= limit.time[0][0]) {

							}
						}
					}

				})
		}
	})

	function onRangeChange([start,end]) {
		const h = Math.floor(dayjs(end).diff(dayjs(start),'hour',true))
		const m = Math.floor(dayjs(end).diff(dayjs(start),'minute',true))%60

		console.log(`${Math.floor(h)}h ${m%60}m`);
		tiempo.value = `: ${h}h ${m}m`

		if (h < 3) {
			disabled.value = false
		} else {
			disabled.value = true
		}
	}

	function onRangeOk([start,end]){
		data.hora_inicio = dayjs(start).format('YYYY-MM-DD HH:mm:ss')
		data.hora_fin = dayjs(end).format('YYYY-MM-DD HH:mm:ss')
	}

	const handleOk = async () => {
		if (tipo.value == 'equipo') {
			data.equipo_id = recurso.value.id;
			data.recurso_id = null;
		} else if(tipo.value == 'recurso'){
			data.equipo_id = null;
			data.recurso_id = recurso.value.id;
		}

		cargando.value = true;

		try {
			const response = await axios.post(route('reserva.create'), {...data});
			console.log(response.data);
			if (response.status === 201) {
				message.success('Solicitud de reserva enviada correctamente');
				emitir('close');
			} else {
				throw new Error('Error al reservar')
			}
		} catch (error) {
				message.error('Error al reservar');
				console.log(error);
		} finally {
				cargando.value = false;
		}
	};

	let now = ref(new Date())

	const horas = [
		{ label: '08:00 AM', value: '08:00'},
		{ label: '08:45 AM', value: '08:45'},
		{ label: '09:30 AM', value: '09:30'},
		{ label: '10:15 AM', value: '10:15'},
		{ label: '11:00 AM', value: '11:00'},
		{ label: '11:45 AM', value: '11:45'},
		{ label: '12:30 PM', value: '12:30'},
		{ label: '01:15 PM', value: '13:15'},
		{ label: '02:00 PM', value: '14:00'},
		{ label: '02:45 PM', value: '14:45'},
		{ label: '03:30 PM', value: '15:30'},
		{ label: '04:15 PM', value: '16:15'},
		{ label: '05:00 PM', value: '17:00'},
		{ label: '05:45 PM', value: '17:45'}
	]

	const horasLimit = ref([
		{ label: '08:00 AM a 08:45 AM', color: 'bg-neutral-300', time: [[8,0], [8,45]]}, // Generated by Copilot
		{ label: '08:45 AM a 09:30 AM', color: 'bg-neutral-300', time: [[8,45], [9,30]]}, // Generated by Copilot
		{ label: '09:30 AM a 10:15 AM', color: 'bg-neutral-300', time: [[9,30], [10,15]]}, // Generated by Copilot
		{ label: '10:15 AM a 11:00 AM', color: 'bg-neutral-300', time: [[10,15], [11,0]]}, // Generated by Copilot
		{ label: '11:00 AM a 11:45 AM', color: 'bg-neutral-300', time: [[11,0], [11,45]]}, // Generated by Copilot
		{ label: '11:45 AM a 12:30 PM', color: 'bg-neutral-300', time: [[11,45], [12,30]]}, // Generated by Copilot
		{ label: '12:30 PM a 01:15 PM', color: 'bg-neutral-300', time: [[12,30], [13,15]]}, // Generated by Copilot
		{ label: '01:15 PM a 02:00 PM', color: 'bg-neutral-300', time: [[13,15], [14,0]]}, // Generated by Copilot
		{ label: '02:00 PM a 02:45 PM', color: 'bg-neutral-300', time: [[14,0], [14,45]]}, // Generated by Copilot
		{ label: '02:45 PM a 03:30 PM', color: 'bg-neutral-300', time: [[14,45], [15,30]]}, // Generated by Copilot
		{ label: '03:30 PM a 04:15 PM', color: 'bg-neutral-300', time: [[15,30], [16,15]]}, // Generated by Copilot
		{ label: '04:15 PM a 05:00 PM', color: 'bg-neutral-300', time: [[16,15], [17,0]]}, // Generated by Copilot
		{ label: '05:00 PM a 05:45 PM', color: 'bg-neutral-300', time: [[17,0], [17,45]]} // Generated by Copilot
	])

	const deshabilitarFechas = (current) => {
		return current && current.isBefore(dayjs(), "day");
	};
</script>
<template>
	<Modal v-model:open="props.open" title="Reservación" width="min(620px,100%)" @cancel="emitir('close')" @ok="handleOk">
		<div class="flex w-auto  flex-wrap sm:flex-nowrap sm:justify-end gap-3">
			<!-- portada -->
			<div>
				<Carousel :arrows="true" class="w-44 rounded-lg overflow-hidden self-start">
					<template v-slot:prevArrow>
						<div class="custom-slick-arrow" style="left: 10px; z-index: 1">
							<LeftCircleOutlined />
						</div>
					</template>
					<template v-slot:nextArrow>
						<div class="custom-slick-arrow" style="right: 10px">
							<RightCircleOutlined />
						</div>
					</template>
					<img
						v-if="recurso.fotos.length > 0"
						v-for="foto of recurso.fotos"
						:src="`${foto.ruta}`"
						class="w-44 h-44 object-cover rounded"
					/>
				</Carousel>
				<!-- Area y Laboratorio -->
				<div class="pb-1 text-gray-500 pt-2">
					<div class="flex items-center gap-2">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="none" stroke="#999" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m12 6l-8 4l8 4l8-4zm-8 8l8 4l8-4"/></svg>
						{{recurso.area?.nombre ?? 'Sin definir'}}
					</div>
					<div class="flex items-center gap-2">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="none" stroke="#999" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 3h6m-5 6h4m-4-6v6L6 20a.7.7 0 0 0 .5 1h11a.7.7 0 0 0 .5-1L14 9V3"/></svg>
						{{recurso.area?.laboratorio?.nombre ?? 'Sin definir'}}
					</div>
				</div>
			</div>
			<div class="min-w-96">
				<h3 class="text-2xl font-bold">{{recurso.nombre}} • <span class="text-neutral-400">#{{recurso.codigo}}</span></h3>
				<p>{{recurso.descripcion}}</p>
				<div class="">
					<!-- Detalles de horarios reservados -->
					<div class="border rounded-lg">
						<details class="px-3 py-2 rounded-lg">
							<summary class="">
								<div class="inline-flex gap-4 items-center font-bold justify-between text-green-500">
									<span class="">Horarios reservados</span>
									<svg v-if="cargando" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path fill="currentColor" d="M12,1A11,11,0,1,0,23,12,11,11,0,0,0,12,1Zm0,19a8,8,0,1,1,8-8A8,8,0,0,1,12,20Z" opacity="0.25"/><path fill="currentColor" d="M10.14,1.16a11,11,0,0,0-9,8.92A1.59,1.59,0,0,0,2.46,12,1.52,1.52,0,0,0,4.11,10.7a8,8,0,0,1,6.66-6.61A1.42,1.42,0,0,0,12,2.69h0A1.57,1.57,0,0,0,10.14,1.16Z"><animateTransform attributeName="transform" dur="0.75s" repeatCount="indefinite" type="rotate" values="0 12 12;360 12 12"/></path></svg>
								</div>
							</summary>
							<div>
								<table>
									<tbody>
										<tr v-for="reserva of reservas" :key="reserva.id" class="text-sm">
											<td class="py-1 pr-2">
												<div class="flex items-center gap-2 text-nowrap">
													<ReservaEstado :estado="reserva.estado"/>
													<CalendarOutlined style="font-size: 14px"/>
													{{new Intl.DateTimeFormat('es', { weekday: 'short', month: 'short', day:'numeric'}).format(reserva.hora_inicio)}}
												</div>
											</td>
											<td>
												<div class="flex items-center gap-2 px-2 text-nowrap font-mono">
													<ClockCircleOutlined style="font-size: 14px"/>
													{{new Intl.DateTimeFormat('en', { hour: '2-digit', minute: '2-digit'}).format(reserva.hora_inicio)}}
													<svg  xmlns="http://www.w3.org/2000/svg"  width="20"  height="20"  viewBox="0 0 24 24"  fill="none"  stroke="#888"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-right"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M9 6l6 6l-6 6" /></svg>
													{{new Intl.DateTimeFormat('en', { hour: '2-digit', minute: '2-digit'}).format(reserva.hora_fin)}}
												</div>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</details>
						<div class="grid h-1 gap-1 m-2" style="grid-template-columns: repeat(13, 1fr);">
							<Tooltip v-for="(hora, i) of horasLimit" :key="i" placement="top">
								<template #title>
									<span>🟢 {{hora.label}}</span>
								</template>
								<div :class="`${hora.color} rounded-full col-span-1`"></div>
							</Tooltip>
						</div>
					</div>
					<div class="pt-2">
						<h2 class="text-base font-bold pl-2">Selecciona el dia y la hora {{tiempo}}</h2>
						</div>
						<div class="flex pb-2 gap-2">
							<DatePicker v-model:value="fecha" :disabled-date="deshabilitarFechas"/>
							<Select
								ref="select"
								v-model:value="fecha"
								style="width: 120px"
								@focus="focus"
								@change="handleChange"
							>
								<SelectOption
									v-for="hora in horas"
									:key="hora.value"
									:value="hora.value"
								>{{hora.label}}</SelectOption>
							</Select>
							<Select
								ref="select"
								v-model:value="value1"
								style="width: 120px"
								@change="handleChange"
							>
								<SelectOption
									v-for="hora in horas.slice(0,4)"
									:key="hora.value"
									:value="hora.value"
								>{{hora.label}}</SelectOption>
							</Select>
						</div>
						<p class="flex items-center gap-2 pl-3 text-gray-500 pt-1">
							<InfoCircleOutlined />
							Maximo tiempo 3h de 45m <a :href="'https://wa.me/'+ page.props.adminNumber +'?text=Hola necesito mas tiempo!'" target="_blank" class="text-blue-500 hover:text-blue-600 hover:underline">¿Mas tiempo?</a>
						</p>
					</div>
				</div>
			</div>
		<template #footer>
			<Button key="back" @click="emitir('close')">Cancelar</Button>
			<Button key="submit" type="primary" :loading="cargando" @click="handleOk" :disabled="disabled">Reservar</Button>
		</template>
	</Modal>
</template>
<style scoped>
	* {
		font-family: Geist !important;
	}

	:deep(.slick-slide) {
		text-align: center;
		width: 170px;
		height: 170px;
		line-height: 60px;
		background: #37b87c;
		overflow: hidden;
	}

	:deep(.slick-arrow.custom-slick-arrow) {
		width: 25px;
		height: 25px;
		font-size: 25px;
		color: #fff;
		background-color: rgba(31, 45, 61, 0.11);
		transition: ease all 0.3s;
		opacity: 0.3;
		z-index: 1;
	}
	:deep(.slick-arrow.custom-slick-arrow:before) {
		display: none;
	}
	:deep(.slick-arrow.custom-slick-arrow:hover) {
		color: #fff;
		opacity: 0.5;
	}

	:deep(.slick-slide h3) {
		color: #fff;
	}
</style>
