<?php

namespace App\Http\Controllers;

use App\Models\Reserva;
use Carbon\Carbon;

class ReservaApiController extends Controller
{
    // Generated by Copilot
    public function index($tipo, $id)
    {
        $reservas = [];
        if ($tipo == 'equipo') {
            $reservas = Reserva::where('equipo_id', $id)->get();
        } else if ($tipo == 'recurso') {
            $reservas = Reserva::where('recurso_id', $id)->get();
        }

        $filteredReservas = $reservas->filter(function ($reserva) {
            return now()->timestamp < strtotime($reserva->hora_inicio);;
        });

        return response()->json([
            'data' => $filteredReservas
        ]);
    }
}
