<?php

namespace App\Http\Controllers;

use App\Models\Equipo;
use App\Models\Recurso;
use App\Models\Reserva;
use Illuminate\Http\Request;

class ReservaApiController extends Controller
{
    // Generated by Copilot
    public function index($tipo, $id)
    {
        $reservas = [];
        if ($tipo == 'equipo') {
            $reservas = Reserva::where('equipo_id', $id)->get();
        } else {
            $reservas = Reserva::where('recurso_id', $id)->get();
        }

        return response()->json($reservas);
    }

    public function store(Request $request)
    {
        //
    }

    public function show(string $id)
    {
        //
    }

    public function update(Request $request, string $id)
    {
        //
    }

    public function destroy(string $id)
    {
        //
    }
}
